name: mdaencore-docs
channels:
    - default
    - conda-forge
dependencies:
    # Base depends
    - python
    - pip

    - sphinxcontrib-bibtex
    - docutils >=0.20

    - numpy
    - scipy
    - MDAnalysis
    - cython
    - MDAnalysisTests
    - pytest
    - mdanalysis-sphinx-theme
