name: mdaencore-docs
channels:
dependencies:
    # Base depends
    - python
    - pip

    - sphinx<7.0

    - sphinx_rtd_theme
    - sphinxcontrib-bibtex

    - numpy
    - scipy
    - MDAnalysis
    - MDAnalysisTests
    - pytest
    
    - pip:
        - msmb_theme
