name: mdaencore-docs
channels:
    - default
    - conda-forge
dependencies:
    # Base depends
    - python
    - pip

    - sphinxcontrib-bibtex

    - numpy
    - scipy
    - MDAnalysis
    - cython
    - MDAnalysisTests
    - pytest
    - mdanalysis-sphinx-theme
