name: mdaencore-docs
channels:
    - default
    - conda-forge
dependencies:
    # Base depends
    - python
    - pip

    - docutils >=0.20
    - sphinxcontrib-bibtex=2.5.0
    - mdanalysis-sphinx-theme    

    - numpy
    - scipy
    - MDAnalysis
    - cython
    - MDAnalysisTests
    - pytest
    
