name: mdaencore-docs
channels:
    - default
    - conda-forge
dependencies:
    # Base depends
    - python
    - pip

    - sphinxcontrib-bibtex

    - numpy
    - scipy
    - MDAnalysis
    - MDAnalysisTests
    - pytest

    - pip:
        - mdanalysis-sphinx-theme
